Polybot and Yolo5 files CICD tf

diff --git a/.github/workflows/yolo5-deployment-region.yaml b/.github/workflows/yolo5-deployment-region.yaml
--- a/.github/workflows/yolo5-deployment-region.yaml
+++ b/.github/workflows/yolo5-deployment-region.yaml
@@ -29,20 +29,25 @@ jobs:
         run: |
           export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
           export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
-       # Gets instances id from yolo5 ec2 by their tags
+               
+          # Gets instances id from yolo5 ec2 by their tags    
           INSTANCES_IDS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=shantalberkhof-yolo5-ec2" \
             --query 'Reservations[*].Instances[*].InstanceId' --output text)
-  
-          for instance_id in $INSTANCES_IDS;
-          do
-            state=$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[*].Instances[*].State.Name' --output text)
+          
+          for instance_id in $INSTANCES_IDS; do
+            #state=$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[*].Instances[*].State.Name' --output text)
+            state=$(aws ec2 describe-instances --filters "Name=instance-id,Values=$instance_id" \
+              --query 'Reservations[*].Instances[*].{State:State.Name}' \
+              --output text)  
+
             echo "The instance - $instance_id is in state - $state"
-               
-            if [ "$state" = "terminated" ]; then
-              echo "Instance terminated, skipping."
-            elif [ "$state" = "stopped" ]; then
-              echo "Starting instance $instance_id..."
+            
+            if [ "$state" = "terminated" ]; 
+            then
+              echo "Instance terminated, cannot be started..."
+            elif [ "$state" = "stopped" ]; 
+            then
+              echo "Starting instance..."
               aws ec2 start-instances --instance-ids $instance_id
               aws ec2 wait instance-running --instance-ids $instance_id
             else
@@ -64,37 +69,61 @@ jobs:
       - name: Deploy YOLOv5 to EC2 in specific region
         env:
           AWS_DEFAULT_REGION: ${{ inputs.region-code }}
-          PRIVATE_KEY: ${{ secrets.US_EAST_1_PRIVATE_KEY }}
+          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
         run: |
           cd tf
           # Gets from tfvars file the owner name
-          OWNER=$(grep owner region.us-east-1.tfvars | grep -o '".*"' | sed 's/"//g')
+          OWNER=$(cat region.$AWS_DEFAULT_REGION.tfvars | grep owner |  grep -o '".*"' | sed 's/"//g')
+          
           cd ..
 
           # create .env file with needed values.
-          echo "BUCKET_NAME=tf-$OWNER-images-bucket-us-east-1
+          echo "BUCKET_NAME=tf-$OWNER-images-bucket-$AWS_DEFAULT_REGION
           SQS_QUEUE_NAME=tf-$OWNER-project-queue
-          REGION_NAME=us-east-1
+          REGION_NAME=$AWS_DEFAULT_REGION
           DYNAMODB_TABLE=tf-$OWNER-predictions-dynamodb-table
-          ALB_URL=$OWNER-polybot-us-east-1.int-devops.click:8443" > .env
-
+          ALB_URL=$OWNER-polybot-$AWS_DEFAULT_REGION.int-devops.click:8443" | tr -d ' ' > .env
+          
           # Gets from env only the IPs
           YOLO5_SERVERS_IP=${YOLO5_SERVERS_IP#*:}
           echo "The IPs of running Yolo5 EC2's are- $YOLO5_SERVERS_IP"
-
-          export YOLO5_IMAGE=shantalberkhof/yolo5-aws-project:v2
+          
+          export YOLO5_IMAGE=shantalberkhof/my_yolo5:v2
           echo "yolo5 image - $YOLO5_IMAGE"
-
+          
+          # Creates from secret the private key as file.
           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
 
-          for SERVER_IP in $YOLO5_SERVERS_IP; do
+          # Do the needed actions for every ec2 if its on (has public ip)
+          for SERVER_IP in $(echo $YOLO5_SERVERS_IP); 
+          do
             # Copies .env file to ec2
-            scp -o StrictHostKeyChecking=no -i private_key .env ubuntu@$SERVER_IP:/home/ubuntu/
+            scp -o StrictHostKeyChecking=no -i private_key .env ubuntu@${SERVER_IP}:/home/ubuntu/
             # Connects to ec2
-            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_IP <<EOF
-              YOLO5_IMAGE=shantalberkhof/my_yolo5:v2 # was latest
-              docker stop my_yolo5 || true && docker rm my_yolo5 || true
-              docker run -d --restart always --env-file /home/ubuntu/.env --name my_yolo5 \$YOLO5_IMAGE
-              docker ps | grep my_yolo5 || exit 1
+            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${SERVER_IP} <<EOF
+              YOLO5_IMAGE=shantalberkhof/my_yolo5:v2
+              echo $YOLO5_IMAGE
+              # Deletes old latest image (if exists)
+              docker image ls | grep shantalberkhof/my_yolo5:v2 | grep latest
+              if [ $? -eq 0 ]
+              then
+                docker image rm shantalberkhof/my_yolo5:v2
+              fi 
+              # Deploys new yolo5 version and stops older version (if exists)
+              docker ps | grep yolo5 
+              if [ $? -eq 0 ]
+              then
+                docker stop yolo5 
+                docker rm yolo5 
+              fi 
+              # Starts new docker container from new image
+              docker run -d --restart always --env-file .env --name yolo5 $YOLO5_IMAGE
+              # Verify container's health
+              docker ps | grep yolo5 | grep Up
+              if [ $? -ne 0 ]
+              then
+                echo "docker run operation has failed in $SERVER_IP"
+                exit 1
+              fi
           EOF
           done
